export const apiRoutes = {
  login: '/auth/login',
  changePassword: '/auth/change-password',
  password: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  users: '/users',
  patients: '/patients',
  patientsSearch: '/patients/search',
  sickness: '/sickness',
  nurseReport: '/reports/nurse',
  doctorReport: '/reports/doctor',
  vitalSign: '/vital-signs',
  changeStatus: '/patients/status-history',
  chat: '/chat',
  chatUsers: '/chat/users',
  chart: '/charts',
  notificationAutoPersonal: '/notifications/auto-personal',
  notificationAutoPersonalShow: '/notifications/auto-personal/show',
  notificationIntoxication: '/notifications/intoxication',
  notificationIntoxicationShow: '/notifications/intoxication/show',
};